MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = no
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

TAP_DANCE_ENABLE = yes      # Soporte para TAP DANCE
COMBO_ENABLE = yes          # Combos
CAPS_WORD_ENABLE = yes

EXTRAFLAGS += -flto
SRC += cvfcvf.c

